# Minimal genlayer stubs for `mypy --strict` on contracts/grudge.py.
# These mirror the subset of the GenVM Python SDK the contract uses; they are
# NOT the real SDK (the GenVM runtime provides that at execution time).
import typing
from dataclasses import dataclass as dataclass

# `gl` is a module in the real SDK; the submodule stub keeps `gl.Contract`
# usable as a base class under mypy --strict.
from . import gl as gl

_T = typing.TypeVar("_T")
_K = typing.TypeVar("_K")
_V = typing.TypeVar("_V")

class u32(int):
    def __new__(cls, value: int) -> u32: ...

class u64(int):
    def __new__(cls, value: int) -> u64: ...

class u256(int):
    def __new__(cls, value: int) -> u256: ...

class Address:
    def __init__(self, value: str) -> None: ...
    @property
    def as_hex(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DynArray(typing.Generic[_T]):
    def __class_getitem__(cls, item: typing.Any) -> typing.Any: ...
    def __call__(self) -> DynArray[_T]: ...
    def append(self, item: _T) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T: ...
    def __iter__(self) -> typing.Iterator[_T]: ...

class TreeMap(typing.Generic[_K, _V]):
    def get(self, key: _K) -> _V | None: ...
    def __getitem__(self, key: _K) -> _V: ...
    def __setitem__(self, key: _K, value: _V) -> None: ...
    def __contains__(self, key: _K) -> bool: ...
    def items(self) -> typing.Iterator[tuple[_K, _V]]: ...

def allow_storage(cls: type[_T]) -> type[_T]: ...
